### PR TITLE
Rework -c handling to match POSIX shell specs: rather than being an

### PR DESCRIPTION
**Pull request by boyski**
option which takes a string it's a boolean which says that the upcoming
unparsed string should be executed. The difference is in ordering such
that a command line like this should now work:

pmaudit -c -e [possible other options] "command string"

### CODE REVIEW

**Review by david-a-wheeler — COMMENTED** [review]
A -c can have parameters, and those parameters could include "--". So I think the branches might be better as:

~~~~
if opts.c:
    .... -c handling
elif '--' in sys.argv:
    .... command in params handling
else:
    ... other/query handling
~~~~

**Comment by boyski** [comment]
I don't agree. Can you give an example or point to a reference? Note that
the test is for an entire string 2-char in the list called '--' so if the
command string passed with -c included a '--' it would not be found. I
cannot think of a scenario in which a -- and a -c (as interpreted by the
shell according to POSIX) can coexist. Meanwhile there are cases such as

pmaudit -- some_random_command -c ....

where an unrelated -c could be used with -- and in that case -- should take
precedence.

**Comment by boyski** [comment]
"...  an entire 2-char string ..."

**Comment by boyski** [comment]
Well, there is this:

$ sh -c -- uname
Linux

So it seems kind of indeterminate, but as a practical matter there are two
usage modes (list and string) and IMHO "--" is the best heuristic.

**Comment by david-a-wheeler** [comment]
Per posix....

If -c is present, then the first non option string is the script to run. But there can be other options after the script. The first option is the script name, followed by the arguments passed to the script. Those arguments could include --. E.g.,

sh -c -e "my shell script" scriptname -q -- -z
Where -q is an option, but -z is not because the -- ends the options.

**Comment by david-a-wheeler** [comment]
POSIX spec for sh options is here:

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sh.html

**Comment by boyski** [comment]
The problem is that I'm not going to give up the list mode because that's
what I primarily rely on. You care about shell mode primarily, I care about
list mode primarily, and something has to give. I'm looking for a
deterministic way to distinguish the two but not thinking of one.

**Comment by boyski** [comment]
I'm going to commit this as there's no activity and it seems better than the status quo. Further improvement possible of course.

**Comment by david-a-wheeler** [comment]
Sounds good. I'm on vacation, I thought I'd have time but I have not. Thanks!

**Comment by boyski** [comment]
Yes, and I did this because I'm cleaning up loose ends before going on a
week's vacation myself!

**Pull request merged**
